### ISSUE TITLE
Rebase on Upstream?

### ISSUE THREAD

**Issue by mushishi78** [themes-jekyll/themes-jekyll.github.io#13]
Before Matt resurfaced it was easy to merge in PRs as this fork was ahead of the upstream repo that the PRs were based on. However now the PRs are based on a divergent history, so as far as I know, they have to be merged in manually. That is why currently the following PRs have not been merged:

[#205](https://github.com/mattvh/jekyllthemes/pull/205)
[#208](https://github.com/mattvh/jekyllthemes/pull/208)
[#209](https://github.com/mattvh/jekyllthemes/pull/209)

Would it be easiest to rebase this fork on the current mattvh repo? Or is there a better way to keep up to date?

@jekyllrc/core

**Comment by gynter** [comment]
I'm not sure if rebasing will do any good (except for the new themes), since this repo has features which upstream doesn't have (i.e stars, github metadata, and different thumbnail resolution). If I have a bit free time I'll try to make some useful modifications to upstream too (like removing the dates from front matter). I cannot make any major changes to upstream thou, since those are out of the scope from my agreement with Matt.

**Comment by gynter** [comment]
My idea is to get at least the `_posts` directory into sync with this fork and upstream which should make merging between those easier. But that would probably mean that we have to make changes in our stars and github metadata system, since I don't want to put unneeded (bloated) data to upstream.

**Comment by mushishi78** [comment]
Does rebasing do any harm though? Is there another way to merge in new themes without merging in the changes on the mattvh repo?

Otherwise, I'm just going to ignore new themes for the time being because I'm not going to do it manually.

**Comment by gynter** [comment]
I guess that it shouldn't do any harm so feel free to do that if it makes merging easier.
